import { generateText } from "ai";
import { createWorkersAI } from "workers-ai-provider";

const MODEL = "@cf/qwen/qwen3.8-27b";
const MAX_CONTEXT_MESSAGES = 12;

/**
 * v1 draft agent: single model call over the thread transcript, guided by the
 * mailbox's instructions. No tools yet — that layer comes with triage + MCP.
 * Always writes a draft for human review, even when agent_mode is 'auto'
 * (auto-send stays off until the agent has real guardrails).
 */
export async function generateDraft(env: Env, threadId: number): Promise<void> {
  const thread = await env.DB.prepare(
    `SELECT t.id, t.subject, m.address, m.display_name, m.agent_mode, m.agent_instructions
     FROM threads t JOIN mailboxes m ON m.id = t.mailbox_id WHERE t.id = ?`,
  )
    .bind(threadId)
    .first<{
      id: number;
      subject: string;
      address: string;
      display_name: string | null;
      agent_mode: string;
      agent_instructions: string | null;
    }>();
  if (!thread || thread.agent_mode === "off") return;

  const { results: messages } = await env.DB.prepare(
    `SELECT direction, sent_by, from_address, from_name, text_body, is_auto_submitted
     FROM messages WHERE thread_id = ? ORDER BY created_at DESC LIMIT ?`,
  )
    .bind(threadId, MAX_CONTEXT_MESSAGES)
    .all<{
      direction: string;
      sent_by: string;
      from_address: string;
      from_name: string | null;
      text_body: string | null;
      is_auto_submitted: number;
    }>();

  const latest = messages[0];
  if (!latest || latest.direction !== "inbound" || latest.is_auto_submitted) return;

  const transcript = [...messages]
    .reverse()
    .map((m) => {
      const who =
        m.direction === "outbound"
          ? `${thread.address} (us, sent by ${m.sent_by})`
          : m.from_name
            ? `${m.from_name} <${m.from_address}>`
            : m.from_address;
      return `From: ${who}\n${(m.text_body ?? "").trim()}`;
    })
    .join("\n\n---\n\n");

  const workersai = createWorkersAI({ binding: env.AI });
  const { text } = await generateText({
    model: workersai(MODEL),
    system: [
      `You are the email support agent for ${thread.display_name ?? thread.address} (${thread.address}).`,
      thread.agent_instructions?.trim() || "Be helpful, concise and professional.",
      "Write a reply to the latest message in the thread below.",
      "Reply in the same language the customer used.",
      "Output ONLY the plain-text body of the reply — no subject line, no markdown, no placeholders like [Your Name].",
      "If you don't have enough information to resolve the request, ask a specific clarifying question instead of guessing.",
    ].join("\n"),
    prompt: `Subject: ${thread.subject}\n\n${transcript}`,
  });

  const body = text.trim();
  if (!body) return;

  await env.DB.batch([
    // A newer inbound message supersedes any pending agent draft
    env.DB.prepare(
      `UPDATE drafts SET status = 'discarded'
       WHERE thread_id = ? AND created_by = 'agent' AND status = 'pending'`,
    ).bind(threadId),
    env.DB.prepare(
      `INSERT INTO drafts (thread_id, text_body, created_by, agent_notes, status)
       VALUES (?, ?, 'agent', ?, 'pending')`,
    ).bind(threadId, body, `Generated by ${MODEL} from the last ${messages.length} message(s).`),
  ]);
}
